add classyfire
bionsight/chexmix pull request #6
Opened 2023-01-30 06:56 UTC by elephantoid

add classyfire

2023-01-31 04:52 UTC, pbj8723 requested changes

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/datasources/classyfire.py
> +def query(chem_smiles: List[str], delay: float = 0.2) -> List[str]:
smileses?

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/datasources/classyfire.py
> +from chexmix.utils import iter_grouper
지금 utils에 이함수가없는것같습니다

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/datasources/classyfire.py
> +    for i in iter_grouper(10, chem_smiles):
변수 naming이 안좋은것같습니다

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/datasources/classyfire.py
> +        while True:
while True는 안좋은것같네요

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/datasources/classyfire.py
> +        query_input = "\n".join(i2 for i2 in i)
i2도별로인것같습니다

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +    def reverse(edge_type: str):
뭘 reverse하는지 함수명에 적는게좋을것같습니다

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +            reverse_edge_type = "_" + edge_type
self.reverse 쓰면될것같습니다

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +    def __set_relationship(table, edge_type, s_node, e_node):
type hinting

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +        raise NotImplementedError('This function need to implement on inherited class')
raise NotImplementedError

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +    def from_classyfire_entities(cls, entities):
type hinitng

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +        lineage_ids = []
nodes, lineage, lineage_ids = [], [], [] 이렇게 한번에하는게 좋아보이네요

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +            node_id = HierarchicalGraph.create_node_id(Header.ChemOnto, node['chemont_id'][10:])
열번째부터 슬라이스 하는 이유를 알기위해 chemont_id 포맷을 주석달아주면좋겠네요

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +            name = node['name']
name한번밖에안쓴느것같아서 굳이 선언안해도될것같아요

2023-01-31 04:52 UTC, pbj8723 commented on src/chexmix/graph.py
> +        nodes.append((Header.Chemical + ':' + inchikey[9:], {
create_node_id쓰면 될것같습니다

2023-01-31 05:30 UTC, elephantoid commented on src/chexmix/graph.py
> +            reverse_edge_type = "_" + edge_type
담겨져있는 edge type이 EdgeType class가 아닌 value인 string이여서 쓸 수 없었습니다.

2023-02-01 04:54 UTC, pbj8723 approved these changes
lgtm %c

2023-02-01 04:54 UTC, pbj8723 commented on src/chexmix/graph.py
> +    level_index = ['kingdom', 'superclass', 'class', 'subclass', 'level5', 'level6', 'level7',
대문자

2023-02-01 04:54 UTC, pbj8723 commented on src/chexmix/utils.py
> +def iter_grouper(n, iterable):
type hinting

2023-02-02 07:35 UTC, hojinyoo requested changes
1. 유닛테스트 추가.
2.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/datasources/classyfire.py
> +            f"{CLASSYFIRE_URL}queries.json",
여기에 분리자 추가.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/datasources/classyfire.py
> +def query(chem_smileses: List[str], delay: float = 0.2, n_iter: int = 10) -> List[str]:
n_iter 보다 나은 이름.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/datasources/classyfire.py
> +                f'{CLASSYFIRE_URL}queries/{req_post.json()["id"]}.json', headers=headers
여기도 수정.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/datasources/classyfire.py
> +            if req_get.json()["classification_status"] == "Done":
에러일 경우 warning.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/graph.py
> +class Header:
enum?

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/graph.py
> +        """Get table from graph.
better docsting.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/graph.py
> +    def __set_relationship(table: Dict, edge_type: str, s_node: str, e_node: str):
1. 굳이 함수가 필요한가 싶고
2. private일 경우 _가 하나.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/graph.py
> +            node_id = HierarchicalGraph.create_node_id(Header.ChemOnto, node['chemont_id'][10:])  # CHEMONTID:0000000
1. node['chemont_id'][10:] 보다는 더 나은 표현 필요
2. 아래들도 마찮가지.

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/graph.py
> +    def is_descendant(self, node_id1: str, node_id2: str) -> bool:
그래프 구조에 관한 함수 인데 다른 곳에 있는 것이 더 낫이 않나요?

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/graph.py
> +        nodes.append((HierarchicalGraph.create_node_id(Header.Chemical, inchikey[9:]), {
HierarchicalGraph 대신 cls?

2023-02-02 07:35 UTC, hojinyoo commented on src/chexmix/graph.py
> +class HierarchicalGraph(BioGraph):
HierarchicalGraph 와 BioGraph의 차이?

2023-02-03 02:24 UTC, elephantoid commented on src/chexmix/datasources/classyfire.py
> +            f"{CLASSYFIRE_URL}queries.json",
CLASSFIRE_URL에 마지막에 `/`가 있습니다.

2023-02-03 03:18 UTC, elephantoid commented on src/chexmix/graph.py
> +    def __set_relationship(table: Dict, edge_type: str, s_node: str, e_node: str):
함수로 만들어두는게 코드가독성이 더 높을 것 같습니다.

2023-02-03 06:13 UTC, elephantoid commented on src/chexmix/graph.py
> +class HierarchicalGraph(BioGraph):
기존 코드들을 살펴보니 ClassyfireGraph, MeshGraph, TaxonomyGraph 는 Hierarch구조를 갖기 때문에 따로 명명해준것으로 이해했습니다. 그래서 `is_descendant` 함수를 overwrite하는 구조가 괜찮은 것 같았습니다.
해당 PR이후 graph들도 bionlab/externel에 있는 chexmix와 sync를 맞출예정입니다.

2023-02-03 07:10 UTC, elephantoid commented on src/chexmix/graph.py
> +    def is_descendant(self, node_id1: str, node_id2: str) -> bool:
앞으로 변경될 HierarchiGraphs마다 descendant를 검사하는 방식이 다르기 때문에 일단 해당 graph에 맞춰주는게 좋을 것 같아서 여기에 두었는데 따로 함수를 빼서 uilts 같은데서 각 graph별 is_descendant함수를 구현하는게 나을까요?

2023-02-06 00:28 UTC, hojinyoo reviewed
코멘트 추가.

2023-03-03 02:18 UTC, closed without merging

2023-03-03 02:18 UTC, elephantoid commented
close PR: intergrate chexmix in bionlab repo